name: Build Baccarat Bot EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile baccarat_safe_bot.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: baccarat_bot_exe
          path: dist/baccarat_safe_bot.exe
